-- Active: 1762840752312@@127.0.0.1@3306@simple_transaction_ledger_db
CREATE TABLE accounts (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE,
    balance DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
