CREATE TABLE entries (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_id BIGINT,
    amount DECIMAL(10,2) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE
    
)